name: Greetings from @MrKrishnaAgarwal

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey **#** Welcome to this repo, Congratulations on opening your first issue. Keep Contributing"
        pr-message: "Hey **#** Welcome to this repo, Congratulations on opening your first Pull Requests. Keep Contributing"
